### ISSUE TITLE
Magma Walker and Disabling Enchants

### ISSUE THREAD

**Issue by Fortist** [Selim042/SM-Selim-Enchants#5]
It seems that despite not having the magma walker enchant, you get the effect regardless. I have this problem and the person who made this thread has this problem.

https://www.reddit.com/r/feedthebeast/comments/au48ip/why_does_the_lava_turn_to_magma_around_me_i_dont/

Secondly, disabling enchants dont actually disable them, they just turn red and _maybe_ dont work?
Anything that grabs random enchants will generate them despite being "Disabled"

**Comment by Selim042** [comment]
I do need to know more information, mainly what version of Minecraft and what version of the mod?

**Comment by Selim042** [comment]
![2019-02-24_19 47 59](https://user-images.githubusercontent.com/8419844/53309388-1ff12980-386d-11e9-9fde-c47576b03678.png)
![2019-02-24_19 48 01](https://user-images.githubusercontent.com/8419844/53309389-1ff12980-386d-11e9-89c1-33414ad61da9.png)
While I do appreciate the blame, until you get back with me with more information, that Reddit post seems to not be caused by my mod anyways, at least not in the environment you described (nothing).  Both, with no armor equipped, I do not get the effect, as well as Waila not showing anything when looking at my blocks anyways, unlike what was shown in the post.

Until I have more information, I am going to mark this as invalid.

**Comment by Fortist** [comment]
ohhh that passive agressiveness.
But maybe you found the problem. I dont really care all that much, just a heads up to you.

1.12, whatever the last version you have made for it. etc etc.

**Comment by Selim042** [comment]
Passive aggressive since last time I asked for more information, you replied with "no" and failed to respond as well as having no evidence other than what I have disproved that the bug is mine, which makes it hard to track down and fix.
https://github.com/Selim042/ModJam_5/issues/7
